# Generated by Django 5.0.6 on 2024-06-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_migrate_author_to_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
