# Generated by Django 5.0.6 on 2025-04-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_commentaire_delete_photocomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='categorie',
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='blog.categorie', verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='photo',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='photos', to='blog.categorie', verbose_name='Catégories'),
        ),
    ]
