# Generated by Django 5.0.6 on 2025-03-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Photographe'), ('SUBSCRIBER', 'Visiteur')], max_length=30, verbose_name='Rôle'),
        ),
    ]
